# Generated by Django 4.0.1 on 2022-11-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
